name: Build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - README.md

jobs:
  renderer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: npm ci
      working-directory: ./renderer
    - run: npm run make-index-files
      working-directory: ./renderer
    - run: npm run build
      working-directory: ./renderer
    - uses: actions/upload-artifact@v4
      with:
        name: renderer-dist
        path: ./renderer/dist
        retention-days: 1

  package:
    needs: renderer
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: sudo apt-get update && sudo apt-get install -y libxcb1-dev libxcb-composite0-dev libxcb-randr0-dev libxtst-dev libxkbcommon-dev
    - uses: actions/download-artifact@v4
      with:
        name: renderer-dist
        path: ./renderer/dist
    - run: npm ci
      working-directory: ./main
    - run: npm run build
      working-directory: ./main
    - run: npx electron-builder build --linux AppImage --publish always
      working-directory: ./main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
